#!/usr/bin/env python3
"""Generate configuration.md from metadata.toml inline comments.

Parses the template's metadata.toml file, extracting TOML structure,
inline comments, values, and commented-out optional keys, then produces
a Markdown configuration reference page for MkDocs.

Usage:
    python generate-configuration.py
    # or from project root:
    python docs/web/generate-configuration.py
"""

from __future__ import annotations

import re
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

# Resolve project root (two levels up from this script)
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent

# In v4 the root metadata.toml is gone; each profile is self-contained.
# The English profile is the canonical reference.
METADATA_PATH = PROJECT_ROOT / "template" / "profile_en" / "metadata.toml"

# Static preamble for the generated page
PREAMBLE = """\
# Configuration Reference — profile_<name>/metadata.toml

<!-- This file is auto-generated by generate-configuration.py from
     template/profile_en/metadata.toml. Do not edit manually. -->

Each `profile_<name>/metadata.toml` is a complete, self-contained \
configuration for that CV variant. By changing the key-value pairs, you set \
your name, colors, contact information, layout, and other details. The \
fields below are extracted from the English profile (`profile_en/metadata.toml`); \
every profile in v4 follows the same schema.

Switch profile at compile time via the CLI:

```bash
typst compile cv.typ --input profile=fr
```
"""

# Sections where we only document the pattern once (not per-language)
LANG_SECTION_RE = re.compile(r"^lang\.[a-z]{2}$")

# Pattern for custom-N personal.info sub-tables
CUSTOM_INFO_RE = re.compile(r"^personal\.info\.custom-[a-z0-9-]+$")


@dataclass
class ConfigKey:
    """A single configuration key parsed from metadata.toml."""

    name: str
    section: str  # dotted section path, e.g. "layout.header"
    raw_value: str  # raw string from TOML line
    type: str  # inferred type: string, bool, array, int, float
    description: str  # from comment lines above the key
    optional: bool = False  # True if the key was commented out


@dataclass
class Section:
    """A TOML section with its keys and optional description."""

    path: str  # dotted path, e.g. "layout.header"
    description: str = ""  # comment lines before the section header
    keys: list[ConfigKey] = field(default_factory=list)


def infer_type(raw_value: str) -> str:
    """Infer the TOML type from a raw value string."""
    v = raw_value.strip()
    if v.startswith('"') or v.startswith("'"):
        return "string"
    if v in ("true", "false"):
        return "bool"
    if v.startswith("["):
        return "array"
    if v.startswith("{"):
        return "object"
    if re.match(r"^-?\d+$", v):
        return "int"
    if re.match(r"^-?\d+\.\d+$", v):
        return "float"
    return "string"


def parse_metadata(filepath: Path) -> tuple[list[Section], str]:
    """Parse metadata.toml and return sections with keys, plus raw file content.

    Two-pass approach:
    1. Line-level parse: extract comments, keys, sections
    2. Use raw values for type inference
    """
    raw_content = filepath.read_text()
    lines = raw_content.splitlines()

    sections: list[Section] = []
    current_section = Section(path="")  # root section
    sections.append(current_section)
    comment_block: list[str] = []

    # Track which lang sections we've seen to collapse duplicates
    seen_lang_section = False
    seen_custom_info = False
    skip_section: str | None = None

    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Skip empty lines (but preserve comment blocks)
        if not stripped:
            # If we have a comment block and hit a blank line before a key,
            # it might be a section-level comment. Keep collecting.
            i += 1
            continue

        # Schema directive line
        if stripped.startswith("#:"):
            i += 1
            continue

        # Section header: [something]
        section_match = re.match(r"^\s*\[([^\]]+)\]", stripped)
        if section_match:
            section_path = section_match.group(1).strip()

            # Any section header ends a previous skip
            skip_section = None

            # Collapse lang.<code> sections (except lang.non_latin)
            if LANG_SECTION_RE.match(section_path):
                if seen_lang_section:
                    skip_section = section_path
                    comment_block = []
                    i += 1
                    continue
                else:
                    seen_lang_section = True
                    # Use generic path for docs
                    section_path = "lang.<code>"

            # Collapse custom-N sections
            if CUSTOM_INFO_RE.match(section_path):
                if seen_custom_info:
                    skip_section = section_path
                    comment_block = []
                    i += 1
                    continue
                else:
                    seen_custom_info = True
                    section_path = "personal.info.custom-N"
            desc = "\n".join(comment_block).strip()
            current_section = Section(path=section_path, description=desc)
            sections.append(current_section)
            comment_block = []
            i += 1
            continue

        # Comment line (always process comments, even in skipped sections,
        # because they may describe the next non-skipped section)
        if stripped.startswith("#"):
            # Check if this is a commented-out key assignment: # key = value
            # The value must start with a TOML literal (quoted string, number, bool, array)
            # to distinguish from descriptive comments like "# true = company name..."
            commented_key_match = re.match(
                r'^#\s*([a-zA-Z_][\w-]*)\s*=\s*(".*?"|\'.*?\'|\[.*\]|true|false|\d[\d.]*)(.*)',
                stripped,
            )
            if commented_key_match:
                if skip_section is not None:
                    # In a skipped section — don't add the key
                    comment_block = []
                    i += 1
                    continue

                name = commented_key_match.group(1).strip()
                raw_val = commented_key_match.group(2).strip()
                trailing = commented_key_match.group(3).strip()

                # Extract inline comment from trailing text
                inline_comment = ""
                if trailing.startswith("#"):
                    inline_comment = trailing.lstrip("#").strip()

                desc_parts = list(comment_block)
                if inline_comment:
                    desc_parts.append(inline_comment)
                desc = "\n".join(desc_parts).strip()

                key = ConfigKey(
                    name=name,
                    section=current_section.path,
                    raw_value=raw_val,
                    type=infer_type(raw_val),
                    description=desc,
                    optional=True,
                )
                current_section.keys.append(key)
                comment_block = []
            else:
                # Regular comment — strip the # prefix
                comment_text = stripped.lstrip("#").strip()
                comment_block.append(comment_text)
            i += 1
            continue

        # If we're in a section we're skipping (duplicate lang/custom), skip keys
        if skip_section is not None:
            i += 1
            continue

        # Key assignment: key = value
        key_match = re.match(r"^(\s*)([a-zA-Z_][\w-]*)\s*=\s*(.+)$", stripped)
        if key_match:
            name = key_match.group(2).strip()
            rest = key_match.group(3).strip()

            raw_val, inline_comment = _split_inline_comment(rest)

            desc_parts = list(comment_block)
            if inline_comment:
                desc_parts.append(inline_comment)
            desc = "\n".join(desc_parts).strip()

            key = ConfigKey(
                name=name,
                section=current_section.path,
                raw_value=raw_val,
                type=infer_type(raw_val),
                description=desc,
            )
            current_section.keys.append(key)
            comment_block = []
            i += 1
            continue

        # Anything else — skip
        comment_block = []
        i += 1

    return sections, raw_content


def _split_inline_comment(rest: str) -> tuple[str, str]:
    """Split a TOML value from its trailing inline comment.

    Returns (raw_value, inline_comment). The inline comment has its # prefix stripped.
    Handles quoted strings that may contain # characters.
    """
    # If value starts with a quote, find the closing quote first
    if rest.startswith('"'):
        close = rest.find('"', 1)
        if close != -1:
            after_quote = rest[close + 1 :].strip()
            if after_quote.startswith("#"):
                return rest[: close + 1].strip(), after_quote.lstrip("#").strip()
            return rest.strip(), ""
    elif rest.startswith("["):
        # Array — find closing bracket
        close = rest.rfind("]")
        if close != -1:
            after_bracket = rest[close + 1 :].strip()
            if after_bracket.startswith("#"):
                return rest[: close + 1].strip(), after_bracket.lstrip("#").strip()
            return rest.strip(), ""

    # No quoting — look for # comment marker
    if "#" in rest:
        parts = rest.split("#", 1)
        return parts[0].strip(), parts[1].strip()

    return rest.strip(), ""


def _format_default(raw_value: str) -> str:
    """Format a raw TOML value for display in a Markdown table."""
    v = raw_value.strip()
    if not v:
        return "—"
    return f"`{v}`"


def _format_description(desc: str, optional: bool) -> str:
    """Format description for Markdown table, joining multi-line comments."""
    # Join multiple lines, adding period between sentences if needed
    lines = [line.strip() for line in desc.splitlines() if line.strip()]
    parts = []
    for line in lines:
        if parts and not parts[-1].endswith((".", "!", "?")):
            parts[-1] += "."
        parts.append(line)
    result = " ".join(parts)
    # Escape pipe characters for table cells
    result = result.replace("|", "\\|")
    if optional:
        result = f"*(optional)* {result}"
    return result


# Sections where defaults are example values (not meaningful defaults)
EXAMPLE_VALUE_SECTIONS = {
    "lang.<code>",
    "lang.non_latin",
    "personal.info",
    "personal.info.custom-N",
}


def format_section_md(section: Section) -> str:
    """Format a Section as a Markdown heading + parameter table."""
    lines = []

    # Section heading
    if section.path == "":
        lines.append("### Root")
    elif section.path == "personal.info.custom-N":
        lines.append("### `[personal.info.custom-N]`")
    else:
        lines.append(f"### `[{section.path}]`")
    lines.append("")

    # Section description (if any)
    if section.description:
        lines.append(section.description)
        lines.append("")

    if not section.keys:
        return "\n".join(lines)

    # For some sections, values are examples not meaningful defaults
    use_example_values = section.path in EXAMPLE_VALUE_SECTIONS

    # Parameter table
    lines.append("| Key | Type | Default | Description |")
    lines.append("|-----|------|---------|-------------|")
    for key in section.keys:
        if key.optional or use_example_values:
            default = "—"
        else:
            default = _format_default(key.raw_value)
        desc = _format_description(key.description, key.optional)
        lines.append(f"| `{key.name}` | {key.type} | {default} | {desc} |")
    lines.append("")

    return "\n".join(lines)


def _format_supported_keys_note() -> str:
    """Generate a note about personal.info supported keys."""
    return "See the full example above for all supported keys.\n"


def generate_configuration() -> str:
    """Generate the full configuration.md content."""
    sections, raw_content = parse_metadata(METADATA_PATH)

    parts = []
    parts.append(PREAMBLE)

    # Full TOML example
    parts.append("## Full Example")
    parts.append("")
    parts.append("```toml")
    parts.append(raw_content.strip())
    parts.append("```")
    parts.append("")

    # Key Reference
    parts.append("## Key Reference")
    parts.append("")

    for section in sections:
        md = format_section_md(section)
        if section.path == "personal.info":
            lines = md.split("\n")
            # Insert note about supported keys after section description
            # Find the table start and insert before it
            for idx, line in enumerate(lines):
                if line.startswith("| Key"):
                    lines.insert(idx, _format_supported_keys_note())
                    break
            md = "\n".join(lines)
        parts.append(md)

    return "\n".join(parts)


if __name__ == "__main__":
    output = generate_configuration()
    outfile = SCRIPT_DIR / "docs" / "configuration.md"
    outfile.write_text(output + "\n")
    print(f"Generated {outfile}", file=sys.stderr)
